drop table CATEGORIES purge;

-- Création d'une table avec une colonne identité.
create table CATEGORIES (
  NOCAT        number(3) generated as identity,
  DESIGNATION  varchar2(30)
);

insert into CATEGORIES (DESIGNATION)
values ('Informatique');
insert into CATEGORIES (DESIGNATION)
values ('Bricolage');
select * from CATEGORIES;

-- Interdit d'affecter une valeur à la colonne dans un INSERT
-- ou un UPDATE.
insert into CATEGORIES (NOCAT,DESIGNATION)
values (123,'Livres');
update CATEGORIES set NOCAT = 456 where DESIGNATION = 'Informatique';

-- Recréation de la table avec l'option BY DEFAULT.
drop table CATEGORIES;
create table CATEGORIES (
  NOCAT        number(3) generated by default as identity,
  DESIGNATION  varchar2(30)
);

insert into CATEGORIES (DESIGNATION)
values ('Informatique');
insert into CATEGORIES (DESIGNATION)
values ('Bricolage');
select * from CATEGORIES;

-- Il est maintenant possible d'affecter une valeur (non NULL) à la colonne 
-- dans un INSERT ou un UPDATE.
insert into CATEGORIES (NOCAT,DESIGNATION)
values (123,'Livres');
update CATEGORIES set NOCAT = 456 where DESIGNATION = 'Informatique';
select * from CATEGORIES;

-- Mais pas d'affecter une valeur NULL.
insert into CATEGORIES (NOCAT,DESIGNATION)
values (null,'Bagages');

-- Recréation de la table avec l'option BY DEFAULT ON NULL.
drop table CATEGORIES;
create table CATEGORIES (
  NOCAT        number(3) generated by default on null as identity,
  DESIGNATION  varchar2(30)
);

-- L'identité est maintenant aussi utilisée lors de l'affectation
-- d'une valeur NULL à la colonne dans un INSERT.
insert into CATEGORIES (NOCAT,DESIGNATION)
values (null,'Bagages');
select * from CATEGORIES;
